### PR TITLE
Conqueror-gentx

### PR DESCRIPTION
**Pull request by DasRasyo**

### CODE REVIEW

**Review by taariq — CHANGES_REQUESTED** [review]
Please update your branch with master and resubmit your gentx PR in the gentx folder for validation.

**Comment by taariq** [comment]
In the correct folder and ready for final review.

**Review by verabehr — CHANGES_REQUESTED** [review]
- Confirmed that validator is in genesis list
- Confirmed staking amount is ok
- Confirmed commission is ok

Please copy the .json file into the correct folder https://github.com/palomachain/mainnet/tree/master/cumulet/gentxs

**Comment by verabehr** [comment]
This is a duplicate of https://github.com/palomachain/mainnet/pull/106

**Pull request closed without merging**
