### PR TITLE
upload nodepro-gentx.json

### PR DESCRIPTION
**Pull request by gokmenkutuk**

### CODE REVIEW

**Review by taariq — CHANGES_REQUESTED** [review]
Please update your branch with master and resubmit your gentx PR in the gentx folder for validation.

**Comment by gokmenkutuk** [comment]
hey @taariq is there any missing?

**Comment by verabehr** [comment]
This validator is not in teh initial validator list from https://forum.palomachain.com/t/pip-11-validator-airdrop-on-paloma-mainnet/156

**Comment by taariq** [comment]
@gokmenkutuk this validator is not in the validator airdrop.

**Comment by gokmenkutuk** [comment]
@taariq @verabehr thanks

**Pull request closed without merging**
