### PR TITLE
add KingSuper gentx

### PR DESCRIPTION
**Pull request by aditya-manit**

### CODE REVIEW

**Review by taariq — CHANGES_REQUESTED** [review]
Please update your branch with master and resubmit your gentx PR in the gentx folder for validation.

**Comment by aditya-manit** [comment]
Done

**Comment by taariq** [comment]
In the correct folder and ready for final review.

**Review by verabehr — APPROVED** [review]
- Confirmed that validator is in genesis list - note that validator's address was changed here https://github.com/palomachain/mainnet/pull/53
- Confirmed staking amount is ok
- Confirmed commission is ok
- Folder is ok

**Pull request merged**
