### PR TITLE
Fission Labs GenTx

### PR DESCRIPTION
**Pull request by alexanderbez**

### CODE REVIEW

**Comment by taariq** [comment]
Fission Labs enters the Genesis chat!

**Review by verabehr — CHANGES_REQUESTED** [review]
Please update the stake amount to less than 10 GRAIN

**Comment by taariq** [comment]
@verabehr ready for merge

**Review by verabehr — APPROVED** [review]
- Confirmed that validator is in genesis list
- Confirmed staking amount is ok
- Confirmed commission is ok
- Folder is ok

**Pull request merged**
