### PR TITLE
mahof-gentx

### PR DESCRIPTION
**Pull request by mahofmahof**

### CODE REVIEW

**Comment by taariq** [comment]
In the correct folder and ready for final review.

**Review by verabehr — CHANGES_REQUESTED** [review]
- Confirmed that validator is in genesis list
- Confirmed commission is ok

Changes requested:
- Please update staking amount `please do not use up all your GRAINs for your validator. More than 1 GRAIN, but less than 10 GRAINs so that you have enough grains for gas`
- Please remove the duplicate file cumulet/gentx/mahof.json

**Comment by mahofmahof** [comment]
done

**Review by verabehr — APPROVED** [review]
- Confirmed that validator is in genesis list
- Confirmed staking amount is ok
- Confirmed commission is ok
- Folder is ok

**Pull request merged**
