### PR TITLE
potm gentx

### PR DESCRIPTION
**Pull request by noobinoobitard**

### CODE REVIEW

**Review by taariq — DISMISSED** [review]
Please update your branch with master and resubmit your gentx PR in the gentx folder for validation.

**Comment by noobinoobitard** [comment]
Done

**Comment by taariq** [comment]
In the correct folder and ready for final review.

**Review by verabehr — CHANGES_REQUESTED** [review]
- Confirmed that validator is in genesis list

- Confirmed commission is ok
- Folder is ok

Please update staking amount `please do not use up all your GRAINs for your validator. More than 1 GRAIN, but less than 10 GRAINs so that you have enough grains for gas`

**Comment by noobinoobitard** [comment]
Done

**Review by verabehr — APPROVED** [review]
- Confirmed that validator is in genesis list
- Confirmed staking amount is ok
- Confirmed commission is ok
- Folder is ok

**Pull request merged**
