### PR TITLE
Update silent address and add silent gentx

### PR DESCRIPTION
**Pull request by silentnoname**
I wanna change my address for mainnet. I use my old testnet address to send a transaction that include my new address in memo to verify.
https://paloma.explorers.guru/transaction/08DE981AB320F32209AC8DB6D5E91B5645E50CBC27BEF8201EB5DB06686E7891

### CODE REVIEW

**Comment by taariq** [comment]
In the correct folder and ready for final review.

**Comment by taariq** [comment]
In the correct folder and ready for final review.

**Comment by taariq** [comment]
@verabehr anything need to be done here?

**Review by verabehr — APPROVED** [review]
- Confirmed that validator is in genesis list
- Confirmed staking amount is ok
- Confirmed commission is ok
- Folder is ok

- Address change request confirmed with Taariq

**Pull request merged**
