### PR TITLE
NODEJUMPER Gentx

### PR DESCRIPTION
**Pull request by vbloher**

### CODE REVIEW

**Comment by taariq** [comment]
In the correct folder and ready for final review.

**Review by verabehr — APPROVED** [review]
- Confirmed that validator is in genesis list
- Confirmed staking amount is ok
- Confirmed commission is ok
- Folder is ok

**Comment by taariq** [comment]
@vbloher your branch is out of date with master. please rebase.

**Comment by verabehr** [comment]
Also, we're unable to update this branch which is a requirement for merging. Either update the branch and merge yourself or remove the restriction.

**Comment by hdmiimdh** [comment]
@verabehr see updated please 😇.

**Comment by verabehr** [comment]
thanks

**Pull request merged**
