### PR TITLE
Nodes.Guru gentx

### PR DESCRIPTION
**Pull request by kinrokinro**

### CODE REVIEW

**Comment by kinrokinro** [comment]
@verabehr wallet address should be correct now

**Review by verabehr — CHANGES_REQUESTED** [review]
- Confirmed that validator is in genesis list
- Confirmed commission is ok

Changes requested
- Please update staking amount `please do not use up all your GRAINs for your validator. More than 1 GRAIN, but less than 10 GRAINs so that you have enough grains for gas`
- Please move the .json file into the correct folder https://github.com/palomachain/mainnet/tree/master/cumulet/gentxs

**Comment by taariq** [comment]
@kinrokinro I think we still have some change requests to close.

**Review by verabehr — APPROVED** [review]

**Review by verabehr — APPROVED** [review]
- Confirmed that validator is in genesis list
- Confirmed staking amount is ok
- Confirmed commission is ok
- Folder is ok

**Pull request merged**
