### PR TITLE
Hdmiimdh Gentx

### PR DESCRIPTION
**Pull request by hdmiimdh**

### CODE REVIEW

**Review by taariq — CHANGES_REQUESTED** [review]
Please update your branch with master and resubmit your gentx PR in the gentx folder for validation.

**Comment by hdmiimdh** [comment]
Sure thing.

**Comment by taariq** [comment]
In the correct folder and ready for final review.

**Comment by verabehr** [comment]
This is a duplicate of https://github.com/palomachain/mainnet/pull/78

**Pull request closed without merging**
