### PR TITLE
PPNV Service gentx

### PR DESCRIPTION
**Pull request by sergiomateiko**
COOOOO!)

### CODE REVIEW

**Review by verabehr — CHANGES_REQUESTED** [review]
- Confirmed that validator is in genesis list
- Confirmed staking amount is ok
- Confirmed commission is ok

Please remove duplicate files: 

PPNV_Service.json
gentx-validator/PPNV_Service_gentx.json

**Comment by sergiomateiko** [comment]
done!

**Comment by sergiomateiko** [comment]
done!)

**Review by verabehr — APPROVED** [review]
- Confirmed that validator is in genesis list
- Confirmed staking amount is ok
- Confirmed commission is ok
- Folder is ok

**Pull request merged**
